image: "luciocarreras/sayonara-ubuntu:xenial"
stages:
  - build
  - test
  - deploy

# Build
build-sayonara:
  stage: build
  script: 
    - mkdir build && cd build
    - cmake .. -DWITH_COTIRE=1 -DWITH_TESTS=1
    - make -j8
  artifacts:
    untracked: true
    expire_in: 1 day
  only:
    - master


# Unit tests
test-sayonara:
  stage: test
  dependencies: 
    - build-sayonara
  script:
    - cd build
    - make test
  artifacts:
    when: on_failure
    untracked: true
    expire_in: 2 days
  only:
    - master


# Packages
## Build AppImage
build-sayonara-appimage:
  stage: build
  script: 
    - dist/appimage.sh build
  artifacts:
    untracked: true
    expire_in: 1 day
  only:
#    - tags
    - 27-create-distribution-building-scripts

      
## Deploy AppImage
deploy-sayonara-appimage:
  stage: deploy
  dependencies:
    - build-sayonara-appimage
  script:
    - dist/appimage.sh deploy
  artifacts:
    paths:
      - build/*.AppImage
    expire_in: 2 weeks
  only:
#    - tags
    - 27-create-distribution-building-scripts


## Fedora
deploy-sayonara-fedora:
  image: "luciocarreras/sayonara-fedora:29"
  stage: build
  script:
    - dist/fedora-rpm.sh build-and-deploy
  artifacts:
    paths:
      - rpms/*.rpm
    expire_in: 2 weeks
  only:
    - tags
#    - 27-create-distribution-building-scripts


# Languages
## Create ts file
build-language:
  stage: build
  script:
    - mkdir -p tx
    - lupdate -no-sort -no-obsolete -locations relative -source-language en_US -target-language en_US ./src -ts tx/sayonara_lang_en_US.ts
  artifacts:
    paths:
      - tx/sayonara_lang_en_US.ts
    expire_in: 2 days
 

## Upload ts to transifex
deploy-language:
  stage: deploy
  dependencies:
    - build-language
  script:
    - cd tx
    - export TX_TOKEN="$TX_API_KEY"
    - tx init --token="$TX_API_KEY" --force --no-interactive
    - tx config mapping -r sayonara-player.sayonara_lang_en_US -l en_US -t QT -s en_US -f sayonara_lang_en_US.ts --execute "sayonara_lang_<lang>.ts"
    - tx push -s
  artifacts:
    paths:
      - tx/sayonara_lang_en_US.ts
    expire_in: 2 days
  only:
    - master
    - tags

