image: "luciocarreras/sayonara-appimage:20191005-3"
stages:
  - build
  - test
  - deploy

# Building
build-sayonara:
  stage: build
  script: 
    - mkdir -p build && cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DWITH_COTIRE=1 -DWITH_TESTS=1
    - make -j6
    - make install DESTDIR=AppDir
  artifacts:
    untracked: true
    expire_in: 1 day
  only:
    - master
    - tags

# Unit tests
test-sayonara:
  stage: test
  variables:
    CI_DEBUG_TRACE: "true"
  dependencies: 
    - build-sayonara
  script:
    - cd build
    - make test
  artifacts:
    when: on_failure
    untracked: true
    expire_in: 2 days
  only:
    - master
    - tags

# Upload to transifex
update-language:
  stage: deploy
  script:
    - apt-get update -qq -y && apt-get install -qq -y --no-install-recommends transifex-client
    - mkdir -p tx
    - lupdate -no-lupdate -no-sort -no-obsolete -locations relative -source-language en_US -target-language en_US ./src -ts tx/sayonara_lang_en_US.ts
    - cd tx
    - tx init --token=${TX_API_KEY} --force --no-interactive
    - tx config mapping -r sayonara-player.sayonara_lang_en_US -l en_US -t QT -s en_US -f sayonara_lang_en_US.ts --execute "sayonara_lang_<lang>.ts"
    - tx push -s
  only:
    - master
    - 43-integrate-transifex-into-ci-scripts

# Deploy
deploy-sayonara:
  stage: deploy
  dependencies:
    - build-sayonara
  script:
    - cd build
    - EXTRA_QT_PLUGINS="iconengines,sqldrivers/libqsqlite.so,platforms/libqxcb.so" QMAKE="/usr/lib/x86_64-linux-gnu/qt5/bin/qmake" linuxdeploy-x86_64.AppImage --appdir=AppDir --desktop-file=./AppDir/usr/share/applications/sayonara.desktop --plugin=qt
    - appimagetool-x86_64.AppImage AppDir
  artifacts:
    paths:
      - build/*.AppImagea
    expire_in: 2 weeks
  only:
    - tags

