image: "luciocarreras/sayonara-ubuntu:xenial"
stages:
  - build
  - test
  - deploy

# Building
## AppImage
build-sayonara-appimage:
  stage: build
  script: 
    - dist/appimage.sh build
  artifacts:
    untracked: true
    expire_in: 1 day
  only:
    - master
    - tags

## Fedora
deploy-sayonara-fedora:
  image: "luciocarreras/sayonara-fedora:29"
  stage: build
  script:
    - dist/fedora-rpm.sh build-and-deploy
    - echo ${PWD}
    - ls -l /app
    - ls -l /app/rpms/
    - ls -l /root/rpmbuild/RPMS/x86_64/
  artifacts:
    paths:
      - /root/rpmbuild/RPMS
    expire_in: 2 weeks
  only:
#    - tags
    - 27-create-distribution-building-scripts


# Unit tests
test-sayonara:
  stage: test
  variables:
    CI_DEBUG_TRACE: "true"
  dependencies: 
    - build-sayonara-appimage
  script:
    - dist/appimage.sh test
  artifacts:
    when: on_failure
    untracked: true
    expire_in: 2 days
  only:
    - master
    - tags

# Deploy
deploy-sayonara-appimage:
  stage: deploy
  dependencies:
    - build-sayonara-appimage
  script:
    - dist/appimage.sh deploy
  artifacts:
    paths:
      - build/*.AppImage
    expire_in: 2 weeks
  only:
    - tags


