image: "luciocarreras/sayonara-appimage:20191005-3"
stages:
  - build
  - test
  - deploy

# Building
build-sayonara-appimage:
  stage: build
  script: 
    - dist/appimage.sh build
  artifacts:
    untracked: true
    expire_in: 1 day
  only:
    - master
    - tags


# Unit tests
test-sayonara:
  stage: test
  variables:
    CI_DEBUG_TRACE: "true"
  dependencies: 
    - build-sayonara-appimage
  script:
    - dist/appimage.sh test
  artifacts:
    when: on_failure
    untracked: true
    expire_in: 2 days
  only:
    - master
    - tags

# Deploy
deploy-sayonara-appimage:
  stage: deploy
  dependencies:
    - build-sayonara-appimage
  script:
    - dist/appimage.sh deploy
  artifacts:
    paths:
      - build/*.AppImagea
    expire_in: 2 weeks
  only:
    - tags

 deploy-sayonara-fedora:
   image: "luciocarreras/sayonara-fedora:29"
   stage: deploy
   script:
     - dist/fedora-rpm.sh
   artifacts:
     paths:
       - *.rpm
     expire_in: 2 weeks
   only:
     - tags
     - 27-create-distribution-building-scripts

